# Generated by Django 2.2.3 on 2020-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_gradient',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='elevation_gain',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.CharField(default=300, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='route_duration',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='support_amenities',
            field=models.CharField(choices=[('sag', 'sag'), ('food stops', 'food stops'), ('post-ride feast', 'post-ride feast')], default='sag', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='surface',
            field=models.CharField(choices=[('road', 'road'), ('gravel', 'gravel'), ('mtb', 'mtb')], default='road', max_length=20),
        ),
    ]
